# Generated by Django 5.0.1 on 2024-01-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StockOrder",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "client_order_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("symbol", models.CharField(max_length=10)),
                ("qty", models.DecimalField(decimal_places=6, max_digits=15)),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("buy_minus_sell_plus", "Buy Minus Sell Plus"),
                            ("sell_short", "Sell Short"),
                            ("sell_short_exempt", "Sell Short Exempt"),
                            ("undisclosed", "Undisclosed"),
                            ("cross", "Cross"),
                            ("cross_short", "Cross Short"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("limit", "Limit"),
                            ("stop", "Stop"),
                            ("stop_limit", "Stop Limit"),
                        ],
                        default="market",
                        max_length=20,
                    ),
                ),
                (
                    "time_in_force",
                    models.CharField(
                        choices=[
                            ("day", "Day"),
                            ("gtc", "Good Till Cancelled"),
                            ("opg", "At the Opening"),
                            ("cls", "At the Close"),
                        ],
                        default="day",
                        max_length=10,
                    ),
                ),
                ("status", models.CharField(max_length=20)),
                (
                    "filled_qty",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                (
                    "filled_avg_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("filled_at", models.DateTimeField(blank=True, null=True)),
                ("expired_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("asset_class", models.CharField(blank=True, max_length=20, null=True)),
                ("extended_hours", models.BooleanField(default=False)),
                (
                    "commission",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "Stock order",
                "verbose_name_plural": "Stock orders",
                "db_table": "Stock orders",
                "ordering": ["-created_at"],
            },
        ),
    ]
