# Generated by Django 5.0.1 on 2024-01-28 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock_orders", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stockorder",
            old_name="order_type",
            new_name="type",
        ),
    ]
