# Generated by Django 5.0.1 on 2024-01-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_orders", "0002_rename_order_type_stockorder_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockorder",
            name="created_at",
            field=models.DateTimeField(null=True),
        ),
    ]
