# Generated by Django 5.0.1 on 2024-01-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_orders", "0003_alter_stockorder_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockorder",
            name="updated_at",
            field=models.DateTimeField(null=True),
        ),
    ]
