# Generated by Django 5.0.1 on 2024-01-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_orders", "0004_alter_stockorder_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockorder",
            name="id_order",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="stockorder",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
